service=""
server=""
proxy=""
web=""

[app]
name="kake"

[log]
log_level="debug"

[[db]]
driver="mysql"
dburl="root:mypass@(192.168.1.100:30036)/turing"

[[db]]
driver="redis"
dburl="root:mypass@(192.168.1.100:30036)/turing"

# https://xuri.me/toml-to-go/